name: calgary-ridership
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pandas=2.1.1
  - numpy=1.25.2
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - pip=23.2.1
  - tabulate=0.9.0
